version: '3'

services:
    backend-api:
        build: ./Caarveit-back-end
        ports:
            - 8080:8080
    frontend:
        build: ./Caarve.it-FE
        ports:
            - 3000:3000
        depends_on:
            - backend-api
        
        