version: '3'

services:
    backend-api:
        build: ./Caarveit-BE
        ports:
            - 8080:8080
    frontend:
        build: ./Caarveit-FE
        ports:
            - 3000:3000
        depends_on:
            - backend-api
        
        